# Generated by Django 6.1 on 2026-08-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='watched_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
