# Generated by Django 6.1 on 2026-08-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_watched_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='watched_date',
        ),
    ]
