# Generated by Django 6.1 on 2026-08-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('book', 'Book')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('tmdb', 'TMDB'), ('openlibrary', 'Open Library')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='catalogs', to='catalog.genre')),
            ],
        ),
    ]
