# Generated by Django 6.1 on 2026-08-13 22:04

from django.db import migrations

def create_genres(apps, schema_editor):
    Genre = apps.get_model('catalog', 'Genre')
    names = [
        'Comedy', 'Sci-Fi', 'Romance', 'Horror', 'Western',
        'Thriller', 'Action', 'Fantasy', 'Superhero', 'Disaster',
        'Animation', 'Anime', 'Crime', 'Road', 'Realism', 'Drama',
    ]
    for name in names:
        Genre.objects.get_or_create(name=name)


def remove_genres(apps, schema_editor):
    Genre = apps.get_model('catalog', 'Genre')
    Genre.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_genres, remove_genres),
    ]
