# Generated by Django 6.1 on 2026-08-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('tmdb', 'TMDB'), ('googlebooks', 'Google Books')], default='manual', max_length=20),
        ),
    ]
