# Generated by Django 6.1 on 2026-08-18 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalog_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, choices=[('manual', 'Manual'), ('tmdb', 'TMDB'), ('googlebooks', 'Google Books')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.artist')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.catalog')),
            ],
        ),
    ]
