# Generated by Django 6.1 on 2026-08-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_artist_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
    ]
