# Generated by Django 6.1 on 2026-08-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_artist_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
