# Generated by Django 6.1 on 2026-08-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_catalog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['title', 'media_type'], name='catalog_cat_title_253812_idx'),
        ),
    ]
