# Generated by Django 6.1 on 2026-08-31 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_catalog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='collection_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='collection_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catalog',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
