# Generated by Django 6.1 on 2026-08-31 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_catalog_collection_id_catalog_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
