# Generated by Django 6.1 on 2026-09-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_catalog_vote_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
